In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
from numba import njit, prange

In [2]:
df = pd.read_csv(Path('..', '..', '..', 'data', 'iris_csv.csv'))

for c in df.columns[0:4]:
    df[c] = (df[c]-df[c].mean())/df[c].std()

df['synth1'] = df['petallength']*df['petalwidth']
df['synth2'] = df['sepallength']*df['petallength']
df['synth3'] = df['sepallength']*df['petalwidth']

for name in df['class'].unique():
    df[f'label-{name}'] = df['class'].map(lambda x: 1 if x == name else 0)

In [3]:
np.random.seed(0)

setosa_idxs = np.arange(0, 50)
versicolor_idxs = np.arange(50, 100)
virginica_idxs = np.arange(100, 150)

p = np.random.permutation(np.arange(50))

setosa_train_idxs = setosa_idxs[p[0:10]]
setosa_test_idxs = setosa_idxs[p[10:]]

versicolor_train_idxs = versicolor_idxs[p[0:10]]
versicolor_test_idxs = versicolor_idxs[p[10:]]

virginica_train_idxs = virginica_idxs[p[0:10]]
virginica_test_idxs = virginica_idxs[p[10:]]

feature_columns = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth']
label_columns = ['label-Iris-setosa', 'label-Iris-versicolor', 'label-Iris-virginica']

xTrain = np.vstack([
    df.iloc[setosa_train_idxs][feature_columns],
    df.iloc[versicolor_train_idxs][feature_columns],
    df.iloc[virginica_train_idxs][feature_columns]
])

yTrain = np.vstack([
    df.iloc[setosa_train_idxs][label_columns],
    df.iloc[versicolor_train_idxs][label_columns],
    df.iloc[virginica_train_idxs][label_columns]
])

xTest = np.vstack([
    df.iloc[setosa_test_idxs][feature_columns],
    df.iloc[versicolor_test_idxs][feature_columns],
    df.iloc[virginica_test_idxs][feature_columns]
])

yTest = np.vstack([
    df.iloc[setosa_test_idxs][label_columns],
    df.iloc[versicolor_test_idxs][label_columns],
    df.iloc[virginica_test_idxs][label_columns]
])

In [4]:
def sigmoid(x: np.ndarray) -> float:
    return 1/(1+np.exp(-x))


@njit(fastmath=True)
def sigmoid_jit(x: np.ndarray) -> float | np.ndarray:
    return 1/(1+np.exp(-x))


@njit(fastmath=True)
def dSigmoid_jit(x: np.ndarray) -> float | np.ndarray:
    y = 1/(1+np.exp(-x))
    return y*(1-y)

In [5]:
@njit(fastmath=True)
def grads(xBatch: np.ndarray, yBatch: np.ndarray, w: np.ndarray, b: np.ndarray) -> tuple[np.ndarray]:
    n = xBatch.shape[0]

    dw = np.zeros(w.shape)
    db = np.zeros(b.shape)
    
    for i in prange(n):
        y = sigmoid_jit(xBatch[i] @ w + b)
        dw += (y - yBatch[i]) * np.atleast_2d(xBatch[i]).T
        db += y - yBatch[i]
    
    return (dw, db)

class Perceptron:
    def __init__(self, nIn: int, nOut: int) -> None:
        self.nIn = nIn
        self.nOut = nOut
        self.w: np.ndarray = np.random.uniform(-1, 1, (nIn, nOut))
        self.b: np.ndarray = np.zeros((nOut))

    def predict(self, x:np.ndarray) -> np.ndarray:
        return sigmoid(x @ self.w + self.b)

    def train(self, xTrain: np.ndarray, yTrain: np.ndarray, lr, batch_size, max_iter) -> None:
        n = xTrain.shape[0]

        for i in range(max_iter):
            idxs = np.random.choice(a=np.arange(n), size=batch_size, replace=False)

            dw, db = grads(xTrain[idxs], yTrain[idxs], self.w, self.b)
            
            self.w -= lr*dw
            self.b -= lr*db

    def loss(self, x: np.ndarray, y: np.ndarray) -> float:        
        Ypred = np.array([self.predict(xi) for xi in x])
        losses = -1 * (y*np.log(Ypred) + (1-y)*np.log(1-Ypred))
        h = 1/self.nOut * np.sum(losses, axis=1)
        return 1/y.shape[0] * np.sum(h)

In [6]:
nIn = 4
nOut = 3

learning_rate = 1e-2
batch_size = 20
max_iter = 3000

model = Perceptron(nIn, nOut)

print('untrained loss: ', model.loss(xTest, yTest).round(3))

model.train(
    xTrain,
    yTrain,
    learning_rate,
    batch_size,
    max_iter
)

print('trained loss: ', model.loss(xTest, yTest).round(3))

TP_count = 0
for x, y in zip(xTest, yTest):
    yPred = model.predict(x)
    TP_count += 1 if np.argmax(y) == np.argmax(yPred) else 0

accuracy = TP_count / xTest.shape[0]
print('accuracy: ', accuracy)

untrained loss:  0.606
trained loss:  0.219
accuracy:  0.925


In [7]:
for x,y in zip(xTest, yTest):
    print(y, model.predict(x).round(2))

[1 0 0] [1.   0.01 0.  ]
[1 0 0] [1.   0.09 0.  ]
[1 0 0] [1.   0.06 0.  ]
[1 0 0] [1.   0.28 0.  ]
[1 0 0] [1.   0.03 0.  ]
[1 0 0] [1.  0.1 0. ]
[1 0 0] [1.   0.01 0.  ]
[1 0 0] [1.   0.16 0.  ]
[1 0 0] [1.   0.04 0.  ]
[1 0 0] [1.   0.22 0.  ]
[1 0 0] [1. 0. 0.]
[1 0 0] [1.   0.26 0.  ]
[1 0 0] [1.   0.03 0.  ]
[1 0 0] [1.   0.01 0.  ]
[1 0 0] [1.   0.15 0.  ]
[1 0 0] [1.   0.12 0.  ]
[1 0 0] [1.   0.02 0.  ]
[1 0 0] [1.   0.32 0.  ]
[1 0 0] [1.   0.23 0.  ]
[1 0 0] [1.   0.28 0.  ]
[1 0 0] [1.   0.02 0.  ]
[1 0 0] [1.   0.04 0.  ]
[1 0 0] [1.   0.04 0.  ]
[1 0 0] [1.  0.1 0. ]
[1 0 0] [1.   0.21 0.  ]
[1 0 0] [1.  0.3 0. ]
[1 0 0] [1.   0.28 0.  ]
[1 0 0] [1.   0.24 0.  ]
[1 0 0] [1.   0.07 0.  ]
[1 0 0] [1.   0.06 0.  ]
[1 0 0] [1.   0.04 0.  ]
[1 0 0] [1.   0.02 0.  ]
[1 0 0] [1.   0.03 0.  ]
[1 0 0] [1.   0.28 0.  ]
[1 0 0] [1.  0.1 0. ]
[1 0 0] [1.   0.05 0.  ]
[1 0 0] [1.   0.24 0.  ]
[1 0 0] [1.   0.06 0.  ]
[1 0 0] [1.   0.16 0.  ]
[1 0 0] [1.   0.04 0.  ]
[0 1 0] [0.   0.77