In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
from numba import njit, prange

In [2]:
df = pd.read_csv(Path('..', '..', '..', 'data', 'iris_csv.csv'))

for c in df.columns[0:4]:
    df[c] = (df[c]-df[c].mean())/df[c].std()

df['synth1'] = df['petallength']*df['petalwidth']
df['synth2'] = df['sepallength']*df['petallength']
df['synth3'] = df['sepallength']*df['petalwidth']

for name in df['class'].unique():
    df[f'label-{name}'] = df['class'].map(lambda x: 1 if x == name else 0)

In [3]:
np.random.seed(0)

setosa_idxs = np.arange(0, 50)
versicolor_idxs = np.arange(50, 100)
virginica_idxs = np.arange(100, 150)

p = np.random.permutation(np.arange(50))

setosa_train_idxs = setosa_idxs[p[0:10]]
setosa_test_idxs = setosa_idxs[p[10:]]

versicolor_train_idxs = versicolor_idxs[p[0:10]]
versicolor_test_idxs = versicolor_idxs[p[10:]]

virginica_train_idxs = virginica_idxs[p[0:10]]
virginica_test_idxs = virginica_idxs[p[10:]]

feature_columns = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth']
label_columns = ['label-Iris-setosa', 'label-Iris-versicolor', 'label-Iris-virginica']

xTrain = np.vstack([
    df.iloc[setosa_train_idxs][feature_columns],
    df.iloc[versicolor_train_idxs][feature_columns],
    df.iloc[virginica_train_idxs][feature_columns]
])

yTrain = np.vstack([
    df.iloc[setosa_train_idxs][label_columns],
    df.iloc[versicolor_train_idxs][label_columns],
    df.iloc[virginica_train_idxs][label_columns]
])

xTest = np.vstack([
    df.iloc[setosa_test_idxs][feature_columns],
    df.iloc[versicolor_test_idxs][feature_columns],
    df.iloc[virginica_test_idxs][feature_columns]
])

yTest = np.vstack([
    df.iloc[setosa_test_idxs][label_columns],
    df.iloc[versicolor_test_idxs][label_columns],
    df.iloc[virginica_test_idxs][label_columns]
])

In [8]:
@njit(fastmath=True)
def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1/(1+np.exp(-x))


@njit(fastmath=True)
def dSgmoid(x: np.ndarray) -> np.ndarray:
    y = 1/(1+np.exp(-x))
    return y*(1-y)


@njit(fastmath=True)
def grads(xBatch: np.ndarray, yBatch: np.ndarray, w: np.ndarray, b: np.ndarray) -> tuple[np.ndarray]:
    n = xBatch.shape[0]
    nOut = w.shape[1]

    dw = np.zeros(w.shape)
    db = np.zeros(b.shape)
    
    for i in prange(n):
        u = xBatch[i] @ w + b
        y = sigmoid(u)

        dLdu = 2/nOut * (y-yBatch[i]) * dSgmoid(u)
        
        dw += np.outer(xBatch[i], dLdu)
        db += dLdu
    
    return dw, db

class Perceptron:
    def __init__(self, nIn: int, nOut: int) -> None:
        self.nIn = nIn
        self.nOut = nOut
        self.w: np.ndarray = np.random.uniform(-1, 1, (nIn, nOut))
        self.b: np.ndarray = np.zeros((nOut))


    def predict(self, x:np.ndarray) -> np.ndarray:
        return sigmoid(x @ self.w + self.b)


    def train(self, xTrain: np.ndarray, yTrain: np.ndarray, lr, batch_size, max_iter) -> None:
        n = xTrain.shape[0]

        for j in range(max_iter):
            idxs = np.random.choice(a=np.arange(n), size=batch_size, replace=False)

            dw, db = grads(xTrain[idxs], yTrain[idxs], self.w, self.b)
            
            self.w -= lr*dw
            self.b -= lr*db
        
    
    def loss(self, x: np.ndarray, y: np.ndarray) -> float:        
        yPred = np.array([self.predict(xi) for xi in x])
        d = 1/self.nOut * np.linalg.norm(y-yPred, axis=1)
        return 1/y.shape[0] * np.sum(d)

In [9]:
nIn = 4
nOut = 3

learning_rate = 1e-2
batch_size = 30
max_iter = 5000

model = Perceptron(nIn, nOut)

print('untrained loss: ', model.loss(xTest, yTest).round(4))

model.train(
    xTrain,
    yTrain,
    learning_rate,
    batch_size,
    max_iter
)

print('trained loss: ', model.loss(xTest, yTest).round(4))

TP_count = 0
for x,y in zip(xTest, yTest):
    yPred = model.predict(x)
    TP_count += 1 if np.argmax(y) == np.argmax(yPred) else 0

accuracy = TP_count / xTest.shape[0]
print('accuracy: ', accuracy)

untrained loss:  0.3689
trained loss:  0.1234
accuracy:  0.9


In [6]:
for x,y in zip(xTest, yTest):
    print(y, model.predict(x).round(2))

[1 0 0] [1.   0.03 0.  ]
[1 0 0] [0.99 0.18 0.  ]
[1 0 0] [0.99 0.11 0.  ]
[1 0 0] [0.99 0.33 0.  ]
[1 0 0] [0.99 0.08 0.  ]
[1 0 0] [0.99 0.16 0.  ]
[1 0 0] [1.   0.04 0.  ]
[1 0 0] [0.98 0.24 0.  ]
[1 0 0] [0.99 0.09 0.  ]
[1 0 0] [0.99 0.23 0.  ]
[1 0 0] [1.   0.01 0.  ]
[1 0 0] [0.98 0.29 0.  ]
[1 0 0] [1.   0.05 0.  ]
[1 0 0] [1.   0.03 0.  ]
[1 0 0] [0.99 0.16 0.  ]
[1 0 0] [0.98 0.22 0.  ]
[1 0 0] [0.98 0.05 0.  ]
[1 0 0] [0.99 0.31 0.  ]
[1 0 0] [0.99 0.24 0.  ]
[1 0 0] [0.97 0.36 0.  ]
[1 0 0] [0.99 0.04 0.  ]
[1 0 0] [0.99 0.09 0.  ]
[1 0 0] [0.99 0.08 0.  ]
[1 0 0] [0.99 0.18 0.  ]
[1 0 0] [0.98 0.3  0.  ]
[1 0 0] [0.99 0.35 0.  ]
[1 0 0] [0.99 0.33 0.  ]
[1 0 0] [0.99 0.21 0.  ]
[1 0 0] [0.99 0.1  0.  ]
[1 0 0] [0.97 0.12 0.  ]
[1 0 0] [0.99 0.13 0.  ]
[1 0 0] [0.99 0.05 0.  ]
[1 0 0] [1.   0.05 0.  ]
[1 0 0] [0.99 0.33 0.  ]
[1 0 0] [0.99 0.16 0.  ]
[1 0 0] [1.   0.08 0.  ]
[1 0 0] [0.99 0.25 0.  ]
[1 0 0] [0.99 0.12 0.  ]
[1 0 0] [0.99 0.19 0.  ]
[1 0 0] [0.99 0.06 0.  ]
