In [1]:
import math
import numpy as np

In [2]:
def softmax(x: np.ndarray) -> np.ndarray:
    y = np.exp(x)
    return y/np.sum(y)

In [3]:
n_words = 3
embedding_size = 4
hidden_size = 2

In [4]:
E = np.random.uniform(-1, 1, (n_words, embedding_size))

In [5]:
Wq = np.random.uniform(-1, 1, (embedding_size, hidden_size))
Wk = np.random.uniform(-1, 1, (embedding_size, hidden_size))
Wv = np.random.uniform(-1, 1, (embedding_size, embedding_size))

In [6]:
Q = E @ Wq
K = E @ Wk
V = E @ Wv

print(Q.shape)
print(K.shape)
print(V.shape)

(3, 2)
(3, 2)
(3, 4)


In [7]:
A = (Q @ K.T) / math.sqrt(hidden_size)
A = np.apply_along_axis(softmax, 0, A)
print(A.shape)
print(A, '\n')

dE = A @ V
print(dE.shape)
print(dE, '\n')

(3, 3)
[[0.2968191  0.27833337 0.27192221]
 [0.26298742 0.3256469  0.24927931]
 [0.44019348 0.39601972 0.47879848]] 

(3, 4)
[[ 0.57994405 -0.20122441 -0.70590924 -0.48999976]
 [ 0.58440395 -0.16330791 -0.6950645  -0.49405901]
 [ 0.91486992 -0.38593245 -1.11385777 -0.71585328]] 



In [8]:
print(E, '\n')
print(dE, '\n')
print(E+dE)

[[ 0.25266847 -0.6107121   0.38934743 -0.21905614]
 [-0.24570053 -0.04980595  0.3886175  -0.59436386]
 [-0.71103487 -0.24618788  0.97888456  0.84836788]] 

[[ 0.57994405 -0.20122441 -0.70590924 -0.48999976]
 [ 0.58440395 -0.16330791 -0.6950645  -0.49405901]
 [ 0.91486992 -0.38593245 -1.11385777 -0.71585328]] 

[[ 0.83261252 -0.81193651 -0.31656181 -0.7090559 ]
 [ 0.33870342 -0.21311386 -0.306447   -1.08842287]
 [ 0.20383505 -0.63212033 -0.13497321  0.13251461]]
